spring.application.name=springboot-aop
management.endpoints.web.exposure.include=health,info
management.info.env.enabled=true

info.app.name= aplicacion aop
info.app.description=aplicacion usando aop
info.app.version=1.0.0